### ISSUE TITLE
Backend error while trying to sign up with VK

### ISSUE THREAD

**Issue by str1nker** [squadster/squadster-api#17]
Seems like small parsing error at the backend with specific data from VK

![image](https://user-images.githubusercontent.com/33372879/75122286-16331980-56ad-11ea-8e0b-47b7c057c5e4.png)

**Comment by mirterious** [comment]
We already fixed this on saturday, make sure that you have latest changes on your local machine.

If problem still exist, please in `iex -S mix phx.server` try to debug data, that come from vk.
Insert `require IEx; IEx.pry` before `lib/squadster/helpers/dates.ex:4` and run authentication again, then in your shell check `string_date` and try `Timex.parse!(string_date, "%-d.%-m.%Y", :strftime)`
If it fall to the error, send us traceback and we will fix it ASAP

**Comment by str1nker** [comment]
Thanks for hands up! Everything works after pulling
