### ISSUE TITLE
Delete session endpoint doesn't work

### ISSUE THREAD

**Issue by str1nker** [squadster/squadster-api#19]
Delete request on /api/auth

![image](https://user-images.githubusercontent.com/33372879/75198532-ec8ff600-5771-11ea-8c44-50e9cc7036af.png)
![image](https://user-images.githubusercontent.com/33372879/75198576-0598a700-5772-11ea-9baf-68a0fc80e098.png)

**Comment by ARtoriouSs** [comment]
Looks like you don't prepend your token header with "Bearer"
It should be `Authentication: "Bearer YOUR_TOKEN"`
